server:
  port: 0

statsServer:
  id: stats-server

spring:
  datasource:
    url: jdbc:postgresql://localhost:6666/category
    username: category
    password: category
  jpa:
    properties:
      hibernate:
        default_schema: public
        format_sql: false
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.PostgreSQLDialect