server:
  port: 0

statsServer:
  id: stats-server

spring:
  datasource:
    url: jdbc:postgresql://localhost:8888/user
    username: user
    password: user
  jpa:
    properties:
      hibernate:
        default_schema: public
        format_sql: false
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.PostgreSQLDialect