server:
  port: 8080

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: category-service
          uri: lb://CATEGORY-SERVICE
          predicates:
            - Path=/categories/**, /admin/categories/**

        - id: compilation-service
          uri: lb://COMPILATION-SERVICE
          predicates:
            - Path=/compilations/**, /admin/compilations/**

        - id: event-service
          uri: lb://EVENT-SERVICE
          predicates:
            - Path=/events/**, /users/*/events/**, /admin/events/**

        - id: requests-service
          uri: lb://REQUESTS-SERVICE
          predicates:
            - Path=/users/*/requests/**

        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/admin/users/**
