grpc:
  server:
    port: 0
  client:
    hub-router:
      address: "discovery:///hub-router"
      negotiationType: plaintext

kafka:
  bootstrap-servers: localhost:9092

  consumer:
    key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    snapshot-value-deserializer: ru.practicum.avro.deserializer.SensorsSnapshotDeserializer
    snapshot-group-id: snapshots-analyzer-group
    hub-event-value-deserializer: ru.practicum.avro.deserializer.HubEventDeserializer
    hub-event-group-id: hub-event-group

  topics:
    user-action-topic-name: stats.user-actions.v1
    events-similarity-topic-name: stats.events-similarity.v1

logging:
  level:
    ru.practicum.ewm: DEBUG