server:
  port: 0

statsServer:
  id: stats-server

spring:
  datasource:
    url: jdbc:postgresql://localhost:7777/request
    username: request
    password: request
  jpa:
    properties:
      hibernate:
        default_schema: public
        format_sql: false
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.PostgreSQLDialect