server:
  port: 0

grpc:
  server:
    enabled: false
  client:
    collector:
      address: 'discovery:///collector'
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext

statsServer:
  id: stats-server

spring:
  datasource:
    url: jdbc:postgresql://localhost:5555/event
    username: event
    password: event
  jpa:
    properties:
      hibernate:
        default_schema: public
        format_sql: false
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.PostgreSQLDialect